# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseShieldRecipe
  categories:
  - Tools
  completetime: 4

- type: latheRecipe
  abstract: true
  id: BaseTargetRecipe
  categories:
  - Tools
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons
  completetime: 2

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeMelee
  completetime: 2

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipePractice
  completetime: 4

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeSidearm
  completetime: 12

## Recipes

# Clothing
- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  categories:
  - Clothing
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  categories:
  - Clothing
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

- type: latheRecipe
  id: ClothingBackpackHarmpack
  result: ClothingBackpackHarmpack
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Plastic: 1000
    Plasma: 500
    Gold: 500

# Shields
- type: latheRecipe
  parent: BaseShieldRecipe
  id: RiotShield
  result: RiotShield
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  parent: BaseShieldRecipe
  id: TelescopicShield
  result: TelescopicShield
  materials:
    Steel: 300
    Glass: 800

# Targets
- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetHuman
  result: TargetHuman

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetSyndicate
  result: TargetSyndicate

# Tools
- type: latheRecipe
  parent: BaseToolRecipe
  id: Handcuffs
  result: Handcuffs
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseToolRecipe
  id: Zipties
  result: Zipties
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseToolRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  parent: BaseToolRecipe
  id: Flash
  result: Flash
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

## Weapons

# Melee
- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Stunbaton
  result: Stunbaton
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Truncheon
  result: Truncheon
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

# Practice weapons
- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: SmokeGrenade
  result: SmokeGrenade
  materials:
    Steel: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

# Long Guns
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 500
    Uranium: 300

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 350

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500

# Sidearms
- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisabler
  result: WeaponDisabler
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  materials:
    Plastic: 100
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponAKMS
  result: WeaponRifleAk
  materials:
    Wood: 300
    Steel: 12000
    Plasteel: 1200

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMosin
  result: WeaponSniperMosin
  materials:
    Wood: 300
    Steel: 5000
    Plasteel: 100

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLecter
  result: WeaponRifleLecter
  materials:
    Steel: 15000
    Plasteel: 2400

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponM16A2Scoped
  result: WeaponM16A2Scoped
  materials:
    Steel: 16500
    Plasteel: 2500
    Glass: 750

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLecterCash
  result: WeaponRifleLecter
  materials:
    Credit: 550

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponM16A2ScopedCash
  result: WeaponM16A2Scoped
  materials:
    Credit: 900

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: MoeWeaponLMGL6
  result: MoeWeaponLMGL6
  materials:
    Steel: 16500
    Plasteel: 5000
    Glass: 750

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponPistolMk58
  result: WeaponPistolMk58
  materials:
    Steel: 2000
    Plasteel: 150

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponPistolMk58Cash
  result: WeaponPistolMk58
  materials:
    Credit: 65

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponShotgunKammerer
  result: WeaponShotgunKammerer
  materials:
    Wood: 1500
    Steel: 4000
    Plasteel: 400

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLauncherRocket
  result: WeaponLauncherRocket
  materials:
    Steel: 20000
    Plasteel: 2000
    Glass: 1000
    Uranium: 150

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: CartridgeRocket
  result: CartridgeRocket
  materials:
    Steel: 2000
    Plasteel: 300
    Plasma: 350

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLauncherBGMLauncherColony
  result: WeaponLauncherBGMLauncherColony
  materials:
    Steel: 25000
    Plasteel: 5000
    Glass: 1500
    Uranium: 200

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLauncherBGMLauncherColonyCash
  result: WeaponLauncherBGMLauncherColony
  materials:
    Credit: 2750

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: BinocularVehicleCash
  result: BinocularVehicle
  materials:
    Credit: 300

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: BinocularsCash
  result: Binoculars
  materials:
    Credit: 250

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponTurretMoeM2HBColonyCash
  result: WeaponTurretMoeM2HBColony
  materials:
    Credit: 3000

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM2HBCash
  result: WeaponMechM2HB
  materials:
    Credit: 2500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: CartridgeMissileBGM71F
  result: CartridgeMissileBGM71F
  materials:
    Steel: 2500
    Plasteel: 1000
    Plasma: 800

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: CartridgeMissileBGM71FCash
  result: CartridgeMissileBGM71F
  materials:
    Credit: 1500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: CartridgeMissileBGM71DCash
  result: CartridgeMissileBGM71D
  materials:
    Credit: 800

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM60D
  result: WeaponMechM60D
  materials:
    Steel: 2000
    Plasteel: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM60DCash
  result: WeaponMechM60D
  materials:
    Credit: 1300 # Should be cheaper than an infantry m60 i think
    
- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM256Cash
  result: WeaponMechM256
  materials:
    Credit: 12000

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM242Cash
  result: WeaponMechM242
  materials:
    Credit: 6000

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechBGMRackCash
  result: WeaponMechBGMRack
  materials:
    Credit: 4500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM250
  result: WeaponMechM250
  materials:
    Steel: 1000
    Plasteel: 100

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: WeaponMechM250Cash
  result: WeaponMechM250
  materials:
    Credit: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SmokeScreenCartridge
  result: SmokeScreenCartridge
  materials:
    Steel: 1000

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: SmokeScreenCartridgeCash
  result: SmokeScreenCartridge
  materials:
    Credit: 100

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM2HB
  result: WeaponMechM2HB
  materials:
    Steel: 6500
    Plasteel: 1200

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM256
  result: WeaponMechM256
  materials:
    Steel: 9000
    Plasteel: 3500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechBGMRack
  result: WeaponMechBGMRack
  materials:
    Steel: 2500
    Plasteel: 800

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponMechM242
  result: WeaponMechM242
  materials:
    Steel: 4500
    Plasteel: 2500